### ISSUE TITLE
I installed and configured the plugin but the plugin menu didn't show up on the main interface.

### ISSUE THREAD

**Issue by vsme** [strapi-community/strapi-plugin-protected-populate#13]
After installing the plugin, set the content of `config/plugins.js` to the following format:
```
module.exports = () => ({
  'protected-populate': {
    enabled: true,
  },
})
``` 

STRAPI VERSION
v4.10.2

NODE VERSION
v16.14.2

**Comment by Boegie19** [comment]
@vsme did you rebuild the admin
aka run the following command on your strapi project
yarn build

**Comment by vsme** [comment]
> @vsme did you rebuild the admin aka run the following command on your strapi project yarn build

Thank you very much for reminding me. I was running it directly using `develop` command and I thought there was no need to build it.
