### ISSUE TITLE
How to get the locale field?

### ISSUE THREAD

**Issue by panosru** [strapi-community/strapi-plugin-protected-populate#18]
Hi, I believe my issue is related to issue #14, I will try to be as detailed as possible.

Here is my setup:
![image](https://github.com/strapi-community/strapi-plugin-protected-populate/assets/400362/56237b2f-a0cf-4a9a-a4c6-a94b39e00a47)

When I access `/api/books/1` I get:
```json
{
    "data": {
        "id": 1,
        "Title": "My Book",
        "ISBN": "1234354",
        "localizations": [
            {
                "id": 3,
                "Title": "Моя книга",
                "ISBN": "1234354"
            },
            {
                "id": 2,
                "Title": "Το βιβλίο μου",
                "ISBN": "1234354"
            }
        ]
    },
    "meta": {}
}
```

When I access `/api/books/1?locale=ru` I get the same result as above.

If I remove the setting from `protected-populate`* and access either `/api/books/1` or `/api/books/1?locale=ru` I get:
```json
{
    "data": {
        "id": 1,
        "Title": "My Book",
        "ISBN": "1234354",
        "createdAt": "2024-03-04T00:32:22.257Z",
        "updatedAt": "2024-03-04T01:09:16.632Z",
        "publishedAt": "2024-03-04T00:32:24.682Z",
        "locale": "en"
    },
    "meta": {}
}
```

If I access `/api/books/1?populate=*` I get:
```json
{
    "data": {
        "id": 1,
        "Title": "My Book",
        "ISBN": "1234354",
        "createdAt": "2024-03-04T00:32:22.257Z",
        "updatedAt": "2024-03-04T01:09:16.632Z",
        "publishedAt": "2024-03-04T00:32:24.682Z",
        "locale": "en",
        "localizations": [
            {
                "id": 3,
                "Title": "Моя книга",
                "ISBN": "1234354",
                "createdAt": "2024-03-04T00:32:22.257Z",
                "updatedAt": "2024-03-04T01:09:40.874Z",
                "publishedAt": "2024-03-04T01:09:40.873Z",
                "locale": "ru"
            },
            {
                "id": 2,
                "Title": "Το βιβλίο μου",
                "ISBN": "1234354",
                "createdAt": "2024-03-04T00:35:00.604Z",
                "updatedAt": "2024-03-04T01:09:16.632Z",
                "publishedAt": null,
                "locale": "el"
            }
        ]
    },
    "meta": {}
}
```

What I want to get is:
```json
{
    "data": {
        "id": 1,
        "Title": "My Book",
        "ISBN": "1234354",
        "localizations": [
            {
                "id": 3,
                "Title": "Моя книга",
                "ISBN": "1234354",
                "locale": "ru"
            },
            {
                "id": 2,
                "Title": "Το βιβλίο μου",
                "ISBN": "1234354",
                "locale": "el"
            }
        ]
    },
    "meta": {}
}
```

But, I don't see any option in the configuration to include the `locale` attribute in the result.

* About the plugin name, could you rename it to `Protected Populate` in the main menu instead of `protected-populate` it kind of triggers my OCD haha
![image](https://github.com/strapi-community/strapi-plugin-protected-populate/assets/400362/f7063db8-4c40-4b3c-b90c-361509dc5b8d)

Hey, really appreciate your work on this, it is very good and indeed, like you, I too got sick of those query strings to get to the needed result and avoid unnecessary data in responses.

**Comment by Boegie19** [comment]
Will do a test tomorow to see what is causing this and fix it if I can replicate it thanks for the report.

**Comment by panosru** [comment]
wow mate, your response time! You live here? haha 

Thanks a ton! If you need anything else from me to provide as additional data let me know

**Comment by Boegie19** [comment]
Just figured out the issue I forgot to add the local key to the UI. update will be out in a hour or so to fix this.

**Comment by Boegie19** [comment]
@panosru Just publised a new version this should fix your issue if it does not fix it please feel free to reopen the issue.
this adds locale to the options in the plugin interface after updating the plugin and rebuilding the admin
![image](https://github.com/strapi-community/strapi-plugin-protected-populate/assets/34578426/5822c09a-b256-4cb4-a2d7-0b73ed8f7ae3)

**Comment by panosru** [comment]
Thanks a lot mate!

**Comment by Boegie19** [comment]
One final note locale needs to be enabled for everyting where you want to use ?locale
