### ISSUE TITLE
strapi V5 support

### ISSUE THREAD

**Issue by ghmasood** [strapi-community/strapi-plugin-protected-populate#21]
Hello
When can we expect Strapi 5 support?

**Comment by Boegie19** [comment]
Will come soon ish

**Comment by Boegie19** [comment]
@ghmasood sorry for the long wait released a beta version for Strapi V5 `strapi-plugin-protected-populate@2.0.0-beta.1`

**Comment by Boegie19** [comment]
V5 is now officaly suported with the 2.0.1 release.
